name: BMP Image Processor CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libopencv-dev
        
    - name: Build project
      run: |
        make clean
        make
        
    - name: Run the program
      run: |
        make run
